services:
  # PostgreSQL database
  - type: psql
    name: portfolio-db
    plan: free
    ipAllowList: [] # Allows access from anywhere

  # The Django web service
  - type: web
    name: Aiswariya-portfolio
    plan: free
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
      python manage.py seed_data
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: portfolio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will automatically generate a secure key
      - key: PYTHON_VERSION
        value: 3.11.9
