services:
  # A PostgreSQL database service
  - type: database
    name: portfolio-db
    plan: free

  # The Django web service
  - type: web
    name: portfolio-website
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromService:
          type: database
          name: portfolio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ALLOWED_HOSTS
        value: ${RENDER_EXTERNAL_HOSTNAME}