databases:
  - name: portfolio-db
    plan: free

services:
  - type: web
    name: aiswariya3a
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn portfolio.wsgi:application --bind 0.0.0.0:${PORT}
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ALLOWED_HOSTS
        value: "${RENDER_EXTERNAL_HOSTNAME}"