# Generated by Django 5.2.5 on 2025-08-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('tech_stack', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('repo_url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Used to order projects. Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('github_url', models.URLField()),
                ('linkedin_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('LANGUAGE', 'Programming Language'), ('DATABASE', 'Database'), ('TOOL', 'Tool/Framework'), ('DEVOPS', 'DevOps'), ('ML_DL', 'Machine/Deep Learning')], default='TOOL', max_length=10)),
                ('level', models.PositiveIntegerField(default=80, help_text='A percentage from 0 to 100.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Used to order skills. Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
