# Generated by Django 5.2.5 on 2025-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_description',
            field=models.TextField(blank=True, help_text='A short description for SEO.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO.', max_length=300),
        ),
    ]
