# Generated by Django 5.2.5 on 2025-08-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_sitesetting_site_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='social_preview_image',
            field=models.ImageField(blank=True, help_text='A 1200x630px image for social media previews.', null=True, upload_to='social_previews/'),
        ),
    ]
