# Generated by Django 5.2.5 on 2025-08-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_sitesetting_social_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your resume in PDF format.', null=True, upload_to='resumes/'),
        ),
    ]
